# Verwendet das aktuellste Python-Image als Basis für den Container
FROM python:latest

# Fügt das server.py-Skript zum Verzeichnis /server/ im Container hinzu
ADD server.py /provider/

# Setzt das Arbeitsverzeichnis des Containers auf /server/
WORKDIR /provider/
